/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _JOGODAFORCA_H_RPCGEN
#define _JOGODAFORCA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mensagem {
	int acertou;
	int conclusao;
	int dificuldade;
	char palavraChave[46];
	char tentativa;
	char strAster[46];
};
typedef struct mensagem mensagem;

#define JogoDaForca 23
#define VERSAO 1

#if defined(__STDC__) || defined(__cplusplus)
#define menuPrincipal 1
extern  mensagem * menuprincipal_1(mensagem *, CLIENT *);
extern  mensagem * menuprincipal_1_svc(mensagem *, struct svc_req *);
#define Aster 2
extern  mensagem * aster_1(mensagem *, CLIENT *);
extern  mensagem * aster_1_svc(mensagem *, struct svc_req *);
#define checkLetra 3
extern  mensagem * checkletra_1(mensagem *, CLIENT *);
extern  mensagem * checkletra_1_svc(mensagem *, struct svc_req *);
#define Jogo 4
extern  int * jogo_1(mensagem *, CLIENT *);
extern  int * jogo_1_svc(mensagem *, struct svc_req *);
extern int jogodaforca_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define menuPrincipal 1
extern  mensagem * menuprincipal_1();
extern  mensagem * menuprincipal_1_svc();
#define Aster 2
extern  mensagem * aster_1();
extern  mensagem * aster_1_svc();
#define checkLetra 3
extern  mensagem * checkletra_1();
extern  mensagem * checkletra_1_svc();
#define Jogo 4
extern  int * jogo_1();
extern  int * jogo_1_svc();
extern int jogodaforca_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mensagem (XDR *, mensagem*);

#else /* K&R C */
extern bool_t xdr_mensagem ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_JOGODAFORCA_H_RPCGEN */
