/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "jogoDaForca.h"

bool_t
xdr_mensagem (XDR *xdrs, mensagem *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->acertou))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->conclusao))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dificuldade))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->acertou);
		IXDR_PUT_LONG(buf, objp->conclusao);
		IXDR_PUT_LONG(buf, objp->dificuldade);
		}
		 if (!xdr_vector (xdrs, (char *)objp->palavraChave, 46,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->tentativa))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->strAster, 46,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->acertou))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->conclusao))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dificuldade))
				 return FALSE;

		} else {
		objp->acertou = IXDR_GET_LONG(buf);
		objp->conclusao = IXDR_GET_LONG(buf);
		objp->dificuldade = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->palavraChave, 46,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_char (xdrs, &objp->tentativa))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->strAster, 46,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->acertou))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->conclusao))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dificuldade))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->palavraChave, 46,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->tentativa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->strAster, 46,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
