/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "jogoDaForca.h"

mensagem * menuprincipal_1_svc(mensagem *argp, struct svc_req *rqstp){
	static mensagem  result;

	for(int i=0; i!=1; ){
        printf("\nDigite a palavra para ser adivinhada: ");
        fflush(stdin);
        scanf("%s", result.palavraChave);
        printf("\nTem certeza que a palavra para ser adivinhada eh: %s ?\n1 - sim\n0 - nao\n", result.palavraChave);
		fflush(stdin);
        scanf("%d", &i);
        
		/*if(i==1){
            system("clear");
        }*/
    }
	

	return &result;
}

mensagem * aster_1_svc(mensagem *argp, struct svc_req *rqstp){
	static mensagem  result;

	/*
	 * insert server code here
	 */

	return &result;
}

mensagem * checkletra_1_svc(mensagem *argp, struct svc_req *rqstp){
	static mensagem  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t * jogo_1_svc(mensagem *argp, struct svc_req *rqstp){
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
