/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "jogoDaForca.h"

bool_t
xdr_mensagem (XDR *xdrs, mensagem *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->palavraChave, 46,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->tentativa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->strAster, 46,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->acertou))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->conclusao))
		 return FALSE;
	return TRUE;
}
