/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "jogoDaForca.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

mensagem *
menuprincipal_1(mensagem *argp, CLIENT *clnt)
{
	static mensagem clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, menuPrincipal,
		(xdrproc_t) xdr_mensagem, (caddr_t) argp,
		(xdrproc_t) xdr_mensagem, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

mensagem *
aster_1(mensagem *argp, CLIENT *clnt)
{
	static mensagem clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Aster,
		(xdrproc_t) xdr_mensagem, (caddr_t) argp,
		(xdrproc_t) xdr_mensagem, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

mensagem *
checkletra_1(mensagem *argp, CLIENT *clnt)
{
	static mensagem clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, checkLetra,
		(xdrproc_t) xdr_mensagem, (caddr_t) argp,
		(xdrproc_t) xdr_mensagem, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
jogo_1(mensagem *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, Jogo,
		(xdrproc_t) xdr_mensagem, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
