/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "jogoDaForca.h"

mensagem *
menuprincipal_1_svc(mensagem *argp, struct svc_req *rqstp)
{
	static mensagem  result;

	/*
	 * insert server code here
	 */

	return &result;
}

mensagem *
aster_1_svc(mensagem *argp, struct svc_req *rqstp)
{
	static mensagem  result;

	/*
	 * insert server code here
	 */

	return &result;
}

mensagem *
checkletra_1_svc(mensagem *argp, struct svc_req *rqstp)
{
	static mensagem  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
jogo_1_svc(mensagem *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
