/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "jogoDaForca.h"
#include <math.h>

/*
    POSSIVEL RESULTADO DO JOGO
*/
void Perdeu(mensagem * msm){
    printf("\nUma pena, voce perdeu!\nA palavra chave era: %s\n", msm->palavraChave);
}
/*
    POSSIVEL RESULTADO DO JOGO
*/
void Ganhou(mensagem * msm){
    printf("\nParabens, voce acertou!\nA palavra era: %s\n", msm->palavraChave);
}

int MenuPrincipal(mensagem * msm){
    int op=0, qtdLetra;
    for(op;op > 3 || op < 1; ){
        printf("\nQual a dificuldade do jogo?\n1 - Facil\n2 - Medio\n3 - Dificil\n");
        fflush(stdout);
        scanf(" %d", &op);

        if(op > 3 || op < 1)
            printf("\nOpcao Invalida, tente novamente!");
    }
    qtdLetra = (int) strlen(msm->palavraChave);
    
    return Dificuldade(op, qtdLetra);
}

int Dificuldade(int op, int qtdLetra){
    int modDificuldade=0;
    switch(op){
        case 1:
            modDificuldade = ceilf(qtdLetra*3.0/4);
            printf("\nDificuldade selecionada: Facil\nVoce tera %d tentativas\nPressione Enter para iniciar...\n", modDificuldade);
            return modDificuldade;
            break;
        case 2:
            modDificuldade = ceilf(qtdLetra*2.0/4);
            printf("\nDificuldade selecionada: Medio\nVoce tera %d tentativas\nPressione Enter para iniciar...\n", modDificuldade);
            return modDificuldade;
            break;
        case 3:
            modDificuldade = ceilf(qtdLetra/4.0);
            printf("\nDificuldade selecionada: Dificil\nVoce tera %d tentativas\nPressione Enter para iniciar...\n", modDificuldade);
            return modDificuldade;
            break;
        default:
            break;
    }
}

mensagem * aster(mensagem * argp){

    int i=0;
    int temp = (int) strlen(argp->palavraChave);
    for(i; i<temp;i++){
        argp->strAster[i] = '*';
    }
    //argp->strAster[i] = '\0';
    
	return argp;
}

mensagem * checkletra(mensagem * argp){

	for(int i=0; argp->palavraChave[i]!='\0';i++){
        if(argp->tentativa == argp->palavraChave[i]){
            argp->strAster[i] = argp->tentativa;
            argp->acertou = 0;
        }
    }

	return argp;
}

int jogo(mensagem * argp){
    if( strcmp(argp->strAster,argp->palavraChave) == 0 )
        argp->conclusao = 0;
    else
		argp->conclusao = 1;

	return argp->conclusao;
}

void jogodaforca_1(char *host){
	CLIENT *clnt;
	mensagem  * result_1;
	mensagem  menuprincipal_1_arg;
	void  *result_2;
	mensagem  showservidor_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, JogoDaForca, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = menuprincipal_1(&result_1, clnt);
	if (result_1 == (mensagem *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	strcpy(result_1->strAster, "");

	result_1->dificuldade = MenuPrincipal(result_1);

	system("read dummy");
    system("clear");

	result_1 = aster(result_1);
	result_1->conclusao = 1;

	for(int i=0;i<result_1->dificuldade;i++){
        result_1->acertou = 1;
        printf("\nVoce tem: %d tentativa(s)!", result_1->dificuldade-i);
        printf("\nDigite uma letra: ");
        fflush(stdin);
        scanf(" %c", &result_1->tentativa);

        if(result_1->conclusao == 1){
            result_1 = checkletra(result_1);

            printf("\n%s", result_1->strAster);
            printf("\n\n---");
            if(result_1->acertou == 0)
                i--;
        }
        result_1->conclusao = jogo(result_1);

		if (result_1 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
        
        if(result_1->conclusao == 0){
            Ganhou(result_1);
            break;
        }
    }

	if(result_1->conclusao == 1)
        Perdeu(result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]){
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	jogodaforca_1 (host);
exit (0);
}
